---
spring.config.activate.on-profile: local
spring:
  data:
    mongodb:
      uri: ${storage.database.mongo.uri}
      database: ${storage.database.mongo.database}
---
spring.config.activate.on-profile: test
spring:
  data:
    mongodb:
      uri: ${storage.database.mongo.uri}
      database: ${storage.database.mongo.database}
---
spring.config.activate.on-profile: dev
spring:
  data:
    mongodb:
      uri: ${storage.database.mongo.uri}
      database: ${storage.database.mongo.database}